export const ERROR_CODES = Object.freeze({
  // General
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  ENDPOINT_NOT_FOUND: "ENDPOINT_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",

  // Validation
  INVALID_DATE_FORMAT: "INVALID_DATE_FORMAT",
  END_DATE_BEFORE_START_DATE: "END_DATE_BEFORE_START_DATE",
  PAST_BOOKING_DATE: "PAST_BOOKING_DATE",

  // Auth
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED_ADMIN_ONLY: "UNAUTHORIZED_ADMIN_ONLY",

  // Rate limiting
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  TOO_MANY_AUTH_ATTEMPTS: "TOO_MANY_AUTH_ATTEMPTS",

  // Booking / reservation
  ROOM_ALREADY_BOOKED: "ROOM_ALREADY_BOOKED",
  INVALID_ROOM_HOTEL_MATCH: "INVALID_ROOM_HOTEL_MATCH"
});