export const ERROR_CODES = Object.freeze({
    ROOM_ALREADY_BOOKED: "ROOM_ALREADY_BOOKED",
    INVALID_ROOM_HOTEL_MATCH: "INVALID_ROOM_HOTEL_MATCH",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    
    UNAUTHORIZED_ADMIN_ONLY: "UNAUTHORIZED_ADMIN_ONLY",
    ENDPOINT_NOT_FOUND: "ENDPOINT_NOT_FOUND"
});