export const ERROR_CODES = Object.freeze({
  // General
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  ENDPOINT_NOT_FOUND: "ENDPOINT_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",

  // Validation
  INVALID_DATE_FORMAT: "INVALID_DATE_FORMAT",
  END_DATE_BEFORE_START_DATE: "END_DATE_BEFORE_START_DATE",
  PAST_BOOKING_DATE: "PAST_BOOKING_DATE",
  INVALID_HOTEL_INPUT: "INVALID_HOTEL_INPUT",
  INVALID_ROOM_INPUT: "INVALID_ROOM_INPUT",
  INVALID_PRICE: "INVALID_PRICE",                 
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",   
  WEAK_PASSWORD: "WEAK_PASSWORD",
  INVALID_USER_INPUT: "INVALID_USER_INPUT",

  // Auth
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED_ADMIN_ONLY: "UNAUTHORIZED_ADMIN_ONLY",
  INVALID_TOKEN: "INVALID_TOKEN",                 
  TOKEN_EXPIRED: "TOKEN_EXPIRED",                
  USER_NOT_FOUND: "USER_NOT_FOUND",

  // Business Logic & Resources
  HOTEL_ALREADY_EXISTS: "HOTEL_ALREADY_EXISTS",

  // Rate limiting
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  TOO_MANY_AUTH_ATTEMPTS: "TOO_MANY_AUTH_ATTEMPTS",

  // Booking / reservation
  ROOM_ALREADY_BOOKED: "ROOM_ALREADY_BOOKED",
  INVALID_ROOM_HOTEL_MATCH: "INVALID_ROOM_HOTEL_MATCH"
});